[workspace]

members = [
    "binary-search",
    "binary-tree",
    "two-crystal-balls",
    "bubble-sort",
    "linked-list",
    "array-list",
    "recursion",
    "quick-sort",
    "priority-queue",
    "graphs",
]

resolver = "2"
